apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rv-library-ms
  description: Demo service registered in Backstage
  annotations:
    github.com/project-slug: udithadissanayake/rv-library-ms
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
